# opt-in only rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - control_statement
  - empty_count
  - extension_access_modifier
  - overridden_super_call
  - trailing_newline
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - yoda_condition

# paths to include during linting. `--path` is ignored if present.
included: 
  - ToDoOrganizer
  - ToDoOrganizerTests

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods

# Rules run by `swiftlint analyze` (experimental)
analyzer_rules:
  - explicit_self

line_length:
    warning: 150
    error: 180
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
