# opt-in only rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - control_statement
  - empty_count
  - explicit_acl
  - extension_access_modifier
  - force_unwrapping
  - function_default_parameter_at_end
  - overridden_super_call
  - trailing_newline
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - yoda_condition

# paths to include during linting. `--path` is ignored if present.
included: 
  - todo
  - todoTests
  - todoUITests 

# paths to ignore during linting. Takes precedence over `included`.
excluded: 
  - Pods

# Rules run by `swiftlint analyze` (experimental)
analyzer_rules: 
  - explicit_self

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
